// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://trswxezmhvubdhjdheit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyc3d4ZXptaHZ1YmRoamRoZWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzYwMDUsImV4cCI6MjA2OTg1MjAwNX0.gjpErW6l2moiwNqS63usWj2iwTA0OXM_iReffozGIr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);